# Page settings

baseurl = "https://psonneveld.github.io/resume/"
languageCode = "nl-NL"
title = "Curriculum Vitae - Patrick Sonneveld"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "public"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Curriculum Vitae - Patrick Sonneveld"
    author = "Patrick Sonneveld"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Patrick Sonneveld"
        tagline = "Full Stack Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fas fa-envelope"
        url = "mailto: patricksonneveld@gmail.com"
        title = "patricksonneveld@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fas fa-phone"
        url = "tel:+31627376373"
        title = "+31(0)6 - 27 37 63 73"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fab fa-linkedin-in"
        url = "//linkedin.com/in/patrick-sonneveld-9a65152b"
        title = "linkedin.com/psonneveld"

        [[params.contact.list]]
        class = "github"
        icon = "fab fa-github"
        url = "//github.com/psonneveld"
        title = "github.com/psonneveld"

        [[params.contact.list]]
        class = "gitlab"
        icon = "fab fa-gitlab"
        url = "//gitlab.com/psonneveld"
        title = "gitlab.com/psonneveld"

    # Education section
    [params.education]
        enable = true
        title = "Opleiding"

        [[params.education.list]]
        degree = "Game Technologie (Minor)"
        college = "Hogeschool Utrecht"
        dates = "2009 - 2011"

        [[params.education.list]]
        degree = "Media Technologie (HBO)"
        college = "Hogeschool Utrecht"
        dates = "2007 - 2011"

        [[params.education.list]]
        degree = "HAVO Natuur & Techniek"
        college = "Guido de Brès te Amersfoort"
        dates = "2002 - 2007"

    # Languages section
    [params.language]
        enable = true
        title = "Taalvaardigheid"

        [[params.language.list]]
        language = "Nederlands"
        level = "Moedertaal"

        [[params.language.list]]
        language = "Engels"
        level = "Professioneel"

    # Interests section
    [params.interests]
        enable = true
        title = "Interesses"
        [[params.interests.list]]
        interest = "Gamen"
        [[params.interests.list]]
        interest = "Squashen"
        [[params.interests.list]]
        interest = "Darten"
        [[params.interests.list]]
        interest = "Snowboarden"
        
# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Profiel"
        paragraph1 = "29 jaar; Getrouwd en vader van een zoon; Naast mijn liefde voor programmeren hou ik van een goede game of film. Ook ben ik altijd in voor een potje squash."
        paragraph2 = "Op het werk lig ik goed in de groep en probeer ik altijd constructieve oplossingen te vinden die voor iedereen passend zijn. Ik ben altijd geïntresseerd in nieuwe technieken en leer hier graag meer over. Daarom ga ik ook graag een nieuwe uitdaging aan."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Werkervaring"

        [[params.jobs.list]]
        position = "Lead Developer"
        dates = "2015 - Heden"
        company = "Goes & Roos"
        city = "Amersfoort"
        details = "**Goes & Roos, kantoorautomatiseerder voor de makelaardij.** Gezien het bestaande CRM (zie hieronder) verouderd was hebben we met een klein team het systeem van de grond af aan opnieuw opgebouwd. We gebruikte hierbij nieuwere technieken en hosten de app nu in Azure. Naast ontwikkelen van modules ben ik als team lead verantwoordelijk voor de hosting; opzetten van procedures en ontwikkelingen van buitenaf (uitbesteden in binnen- en buitenland, koppelaars, begeleiden van stagiairs). Daarnaast denk ik mee bij ontwikkelingen van nieuwe modules en onderhoud aan de bestaande."
        tech = "ASP.NET MVC; C#; SPA met Angular JS; Javascript; Azure; Git (Gitflow); GitLab"

        [[params.jobs.list]]
        position = "Full Stack Developer"
        dates = "2012 - 2015"
        company = "Goes & Roos"
        city = "Amersfoort"
        details = "**Goes & Roos, kantoorautomatiseerder voor de makelaardij.** Front- en back-end ontwikkelingen voor hun CRM-pakket (Customer relationship management). In eerste half jaar heb ik me vooral met losse projecten bezig gehouden. Denk hierbij aan: Intergratie van VoIP en koppelingen met social media. Daarna ben ik mede-verantwoordelijk geworden voor het ontwikkelen en onderhouden van het crm. Wij hebben grote delen van het systeem herschreven en de mogelijkheden uitgebreid. Een groot onderdeel daarvan was de module voor alle correspondentie van het systeem. Met deze module kunnen makelaars snel en gemakkelijk e-mail/brieven aanmaken aan de hand van eigen templates. Vervolgens worden deze gekoppeld aan de juiste relaties/objecten."
        tech = "Javascript; C#; ASP Classic; Visual Basic; JQuery; NodeJS; Access"

        [[params.jobs.list]]
        position = "Freelancer - Ontwikkelaar/Animator"
        dates = "2011 - 2013"
        company = "Bergman Media Group"
        city = "Gorinchem"
        details = "**Bergman Media Group, Crossmediaspecialist** Aantal opdrachten m.b.t. de jaarlijkse kerstgroet. Aangeleverde assets op gewenste manier animeren en op elkaar laten reageren doormiddel van Actionscript. Verder support bij een aantal kleine projecten gemaakt met Adobe Flash."
        tech = "Adobe Flash; Actionscript"

        [[params.jobs.list]]
        position = "Stagiair - Ontwikkelaar"
        dates = "Feb 2011 - Jun 2010"
        company = "Spacegorillas"
        city = "Utrecht"
        details = "**Spacegorillas gespecialiseerd in multi-touch concepten, ontwerpen en omgevingen.** Ik heb hier een basis platform mogen maken voor een van hun producten. Er moest een gedeelte komen waarmee ze hun apps konden distribueren; En een template waarmee applicaties gemakkelijk op het platform gezet konden worden."
        tech = "Adobe Flash; Actionscript"

        [[params.jobs.list]]
        position = "Stagiair - Ontwikkelaar"
        dates = "Feb 2010 - Jul 2010"
        company = "WeirdBeard Games"
        city = "Amsterdam"
        details = "**WeirdBeard, klein gamestudio in Amsterdam.** Ik heb hier een aantal maanden gewerkt aan een aantal minigames in hun bestaande framework. Verder heb ik hier een aantal websites en RIA's (Rich Internet Applications) onderhouden."
        tech = "Adobe Flash; Actionscript; HTML; CSS; Javascript"

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Vaardigheden"

        [[params.skills.list]]
        skill = "Javascript (ES5, ES6)"
        level = "95%"

        [[params.skills.list]]
        skill = "ASP.NET 4.6 - C#"
        level = "90%"

        [[params.skills.list]]
        skill = "Angular JS"
        level = "90%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "90%"

        [[params.skills.list]]
        skill = "SQL/SQL-Server"
        level = "75%"

        [[params.skills.list]]
        skill = "Azure"
        level = "60%"

        [[params.skills.list]]
        skill = "Git (GitFlow)"
        level = "85%"

        [[params.skills.list]]
        skill = "NodeJS"
        level = "55%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Patrick Sonneveld"
